/**
 * The one place the Servana revenue split is defined.
 *
 * **All revenue generated by the platform is split 80% to the service provider,
 * 20% retained by Servana.** That applies uniformly — the base booking, the
 * transport fee, and on-site additional work all use the same rate. There is no
 * per-service, per-provider or per-revenue-type variation.
 *
 * Before this module the rate was a bare float duplicated across twelve sites in
 * four files (providerController ×5, adminProviderService ×2, adminFinanceService
 * ×3 behind its own private constants, disbursement.service ×2 behind another
 * pair). Two of those were the authoritative payout path and the rest were
 * display; nothing forced them to agree, and changing the rate meant finding all
 * twelve. A split that disagrees with itself is not a rounding problem, it is a
 * provider being shown one number and paid another.
 *
 * Amounts are PHP and are stored as NUMERIC in Postgres, so the arithmetic here
 * is the rounding boundary: round once, to two decimals, at the point of split.
 */

/** Servana's retained share of gross revenue. */
export const SERVANA_COMMISSION_RATE = 0.2;

/** The service provider's share of gross revenue. */
export const PROVIDER_SHARE_RATE = 0.8;

/** Provider share as a whole-number percentage, for display and API responses. */
export const PROVIDER_SHARE_PERCENT = Math.round(PROVIDER_SHARE_RATE * 100);

/** Round a PHP amount to centavos. */
const toCentavos = (n: number) => Math.round(n * 100) / 100;

/**
 * Split a gross amount into Servana's cut and the provider's.
 *
 * `gross` must already include everything the customer was charged for the
 * booking — base price, transport fee, and any PAID additional work. Passing a
 * partial gross is how additional work came to contribute nothing to provider
 * pay for as long as it did.
 */
export const splitRevenue = (gross: number) => {
  const total = toCentavos(Number(gross) || 0);
  const servanaShare = toCentavos(total * SERVANA_COMMISSION_RATE);
  return {
    totalAmount: total,
    servanaShare,
    // Derived by subtraction rather than by a second multiplication, so the two
    // shares always add back to the total exactly. Rounding both independently
    // can leave a stray centavo that reconciliation then has to explain.
    providerShare: toCentavos(total - servanaShare),
  };
};

/** The provider's share of a gross amount. */
export const providerShareOf = (gross: number) => splitRevenue(gross).providerShare;

/** Servana's share of a gross amount. */
export const servanaShareOf = (gross: number) => splitRevenue(gross).servanaShare;
