/**
 * The booking documentation must describe the lifecycle the backend actually
 * implements.
 *
 * A hand-written state machine document is correct on the day it is written and
 * quietly wrong forever after — and a wrong one is worse than none, because it
 * looks authoritative. So the three booking documents are generated by
 * EXECUTING `TRANSITIONS`, `BOOKING_ACTIONS` and `deriveCanonicalState`, and
 * this suite fails if the committed copies have fallen behind.
 *
 * The staleness check alone is not enough. It only proves the files match the
 * generator; it would stay green if the generator stopped emitting a table
 * entirely. So the assertions below also check that each document still
 * CONTAINS the things it exists to publish, and that the machine it was
 * generated from has not shrunk.
 */

import fs from 'fs';
import path from 'path';

import { staleFiles, generateAll } from '../scripts/generate-booking-docs';
import { BOOKING_STATES, TRANSITIONS } from '../src/services/booking/canonicalState';
import { BOOKING_ACTIONS } from '../src/services/booking/transitionExecutor';
import {
  ELIGIBILITY_PIPELINE,
  COMMIT_CRITICAL_STAGES,
  DEFAULT_SERVICE_DURATION_MINS,
  NON_OCCUPYING_STATUSES,
  LEGACY_AUTO_GAP,
} from '../src/services/booking/eligibilityPipeline';
import { ZERO_CANDIDATE_REASONS } from '../src/services/booking/candidateDiagnostics';
import { V1_CONTRACT } from '../src/api/v1/contract';

const read = (rel: string) => fs.readFileSync(
  path.join(__dirname, '..', rel), 'utf8',
).replace(/\r\n/g, '\n');

describe('generated booking documentation', () => {
  it('is not stale', () => {
    const stale = staleFiles();
    expect(
      stale.length ? `stale: ${stale.join(', ')} — run "npm run booking:docs"` : 'up to date',
    ).toBe('up to date');
  });

  it('emits all five documents', () => {
    // A generator that silently stopped producing a file would pass the
    // staleness check above, because there would be nothing to compare.
    expect(generateAll().map((f) => f.relPath).sort()).toEqual([
      'docs/booking/BOOKING_ACTOR_PERMISSION_MATRIX.md',
      'docs/booking/BOOKING_EXPERIENCES_V1_CONTRACT.md',
      'docs/booking/BOOKING_STATE_MACHINE.md',
      'docs/booking/BOOKING_STATUS_MIGRATION_MATRIX.md',
      'docs/booking/JOB_MATCHING_V1_CONTRACT.md',
    ]);
  });

  it('every document carries the do-not-edit header', () => {
    for (const f of generateAll()) {
      expect(f.content).toContain('GENERATED FILE - do not edit by hand');
      expect(f.content).toContain('npm run booking:docs');
    }
  });
});

describe('the state machine document publishes the whole machine', () => {
  const doc = read('docs/booking/BOOKING_STATE_MACHINE.md');

  it('lists every canonical state', () => {
    for (const state of BOOKING_STATES) {
      expect(doc).toContain(`| \`${state}\` |`);
    }
  });

  it('lists every whitelisted transition', () => {
    for (const t of TRANSITIONS) {
      expect(doc).toContain(`| \`${t.from}\` | \`${t.to}\` | \`${t.action}\` |`);
    }
  });

  it('lists every action', () => {
    for (const action of Object.keys(BOOKING_ACTIONS)) {
      expect(doc).toContain(`\`${action}\``);
    }
  });

  it('states the counts, so a shrunken machine is visible in the prose', () => {
    expect(doc).toContain(`${BOOKING_STATES.length} states`);
    expect(doc).toContain(`${TRANSITIONS.length} whitelisted transitions`);
    expect(doc).toContain(`${Object.keys(BOOKING_ACTIONS).length} actions`);
  });

  it('records the executor ordering that the transaction depends on', () => {
    // The properties most easily lost in a later refactor.
    expect(doc).toContain('FOR UPDATE');
    expect(doc).toContain('advisory lock');
    expect(doc).toContain('AFTER the booking row');
    expect(doc).toContain('§45');
  });
});

describe('the permission matrix publishes every actor', () => {
  const doc = read('docs/booking/BOOKING_ACTOR_PERMISSION_MATRIX.md');

  it('covers each action with exactly one owning actor', () => {
    for (const [name, spec] of Object.entries(BOOKING_ACTIONS)) {
      const row = doc.split('\n').find((l) => l.startsWith(`| \`${name}\` |`));
      expect(row).toBeDefined();
      // Exactly one tick per action row: an action with two actors would be an
      // authorization hole, and the matrix would be hiding it.
      expect((row!.match(/✅/g) ?? []).length).toBe(1);
      expect(spec.actor).toBeTruthy();
    }
  });

  it('keeps the two authorization failures distinct', () => {
    expect(doc).toContain('NOT_AUTHORIZED');
    expect(doc).toContain('INVALID_TRANSITION');
  });
});

describe('the migration matrix is derived, not described', () => {
  const doc = read('docs/booking/BOOKING_STATUS_MIGRATION_MATRIX.md');

  it('publishes the ended-assignment rule that caused a real defect', () => {
    // A declined provider read as ASSIGNED and could accept the job again.
    expect(doc).toContain('DECLINED');
    expect(doc).toContain('REASSIGNED');
    expect(doc).toContain('AWAITING_ASSIGNMENT');
  });

  it('publishes the null / undefined worker_uid distinction', () => {
    expect(doc).toContain('`worker_uid` `null`');
    expect(doc).toContain('`worker_uid` `undefined`');
  });

  it('publishes the escalation override and the PAID/CONFIRMED collapse', () => {
    expect(doc).toContain('Escalation outranks everything');
    expect(doc).toContain('promotion trigger');
    expect(doc).toContain('TAB04_OPEN_GAPS.md');
  });

  it('shows an unrecognised status falling back to intake', () => {
    // The fallback is a design decision — surface it to an admin rather than
    // hide it — and an undocumented decision is free to change unnoticed.
    const row = doc.split('\n').find((l) => l.includes('SOME_UNRECOGNISED_STATUS'));
    expect(row).toBeDefined();
    expect(row).toContain('AWAITING_ASSIGNMENT');
  });
});

describe('the job + matching contract publishes what TAB 05 certifies on', () => {
  const doc = read('docs/booking/JOB_MATCHING_V1_CONTRACT.md');

  it('names every canonical job and assignment endpoint with its callers', () => {
    // The cross-platform rule: every capability carries a caller matrix for all
    // five clients, so two platforms doing the same business operation are
    // visibly on the same endpoint or visibly not.
    const entries = V1_CONTRACT.filter(
      (e) => e.domain === 'provider-jobs'
        || /^admin\.bookings\.(assign|reassign|assignmentCandidates)/.test(e.id),
    );
    expect(entries.length).toBeGreaterThanOrEqual(11);
    for (const e of entries) {
      expect(doc).toContain(`${e.method.toUpperCase()} /api/v1${e.path}`);
      expect(doc).toContain(e.domainService);
    }
    for (const label of ['Customer Mobile', 'Customer Web', 'Provider Mobile', 'Provider Web', 'Admin']) {
      expect(doc).toContain(label);
    }
  });

  it('publishes every eligibility stage and marks the commit-critical ones', () => {
    for (const stage of ELIGIBILITY_PIPELINE) {
      expect(doc).toContain(`\`${stage.name}\``);
    }
    for (const stage of COMMIT_CRITICAL_STAGES) {
      expect(doc).toContain(stage);
    }
  });

  it('publishes the capability SQL the executor actually runs', () => {
    // Not a description of it. A paraphrase is exactly how the three
    // disagreeing predicates were able to look identical in prose.
    expect(doc).toContain('employee_services');
    expect(doc).toContain('worker_service_applications');
    expect(doc).toContain("status = 'approved'");
    // And the thing it deliberately does NOT consult.
    expect(doc).toContain('catalog_provider_services');
  });

  it('publishes the overlap rule and the non-occupying statuses', () => {
    // The rule a reader has to be able to apply by hand, not a description of
    // one: the inequality, the half-open property and the duration fallback.
    expect(doc).toContain('existing.start < candidate.end');
    expect(doc).toContain('existing.end > candidate.start');
    expect(doc).toContain(`${DEFAULT_SERVICE_DURATION_MINS} minutes`);
    expect(doc).toContain('duration_mins');
    for (const status of NON_OCCUPYING_STATUSES) {
      expect(doc).toContain(`\`${status}\``);
    }
  });

  it('states what the overlap rule replaced, and why', () => {
    // A contract that only describes the current rule reads as if it were
    // always this way, and the delta is what a reader needs when supply moves.
    expect(doc).toContain('±2 hours');
    expect(doc).toContain('30-minute job');
    expect(doc).toContain('four-hour');
  });

  it('publishes every zero-candidate reason code with an action', () => {
    for (const reason of ZERO_CANDIDATE_REASONS) {
      expect(doc).toContain(`\`${reason.code}\``);
      expect(doc).toContain(reason.actionable);
    }
  });

  it('states the open auto-assignment gap rather than implying completeness', () => {
    // A contract that only lists what works reads as a certification.
    expect(doc).toContain(LEGACY_AUTO_GAP.status);
    for (const stage of LEGACY_AUTO_GAP.missingStages) {
      expect(doc).toContain(stage);
    }
  });

  it('publishes the override audit model, derived from the action declaration', () => {
    // Item 56: reason, actor, previous provider, new provider. The document
    // must name every action that enforces a reason, so an override added
    // without one is visible here rather than only in the executor.
    const enforcing = Object.entries(BOOKING_ACTIONS)
      .filter(([, spec]) => (spec as Record<string, unknown>).requiresReason)
      .map(([name]) => name);

    expect(enforcing).toContain('ADMIN_REASSIGN');
    for (const action of enforcing) {
      expect(doc).toContain(`\`${action}\` refuses to run without a non-empty`);
    }
    expect(doc).toContain('before any write');
  });

  it('explains why admin and provider assignment remain separate endpoints', () => {
    expect(doc).toContain('authorization');
    expect(doc).toContain('bookings.assign_provider');
    expect(doc).toContain('transitionBooking');
  });
});
