/**
 * The booking documentation must describe the lifecycle the backend actually
 * implements.
 *
 * A hand-written state machine document is correct on the day it is written and
 * quietly wrong forever after — and a wrong one is worse than none, because it
 * looks authoritative. So the three booking documents are generated by
 * EXECUTING `TRANSITIONS`, `BOOKING_ACTIONS` and `deriveCanonicalState`, and
 * this suite fails if the committed copies have fallen behind.
 *
 * The staleness check alone is not enough. It only proves the files match the
 * generator; it would stay green if the generator stopped emitting a table
 * entirely. So the assertions below also check that each document still
 * CONTAINS the things it exists to publish, and that the machine it was
 * generated from has not shrunk.
 */

import fs from 'fs';
import path from 'path';

import { staleFiles, generateAll } from '../scripts/generate-booking-docs';
import { BOOKING_STATES, TRANSITIONS } from '../src/services/booking/canonicalState';
import { BOOKING_ACTIONS } from '../src/services/booking/transitionExecutor';

const read = (rel: string) => fs.readFileSync(
  path.join(__dirname, '..', rel), 'utf8',
).replace(/\r\n/g, '\n');

describe('generated booking documentation', () => {
  it('is not stale', () => {
    const stale = staleFiles();
    expect(
      stale.length ? `stale: ${stale.join(', ')} — run "npm run booking:docs"` : 'up to date',
    ).toBe('up to date');
  });

  it('emits all three documents', () => {
    // A generator that silently stopped producing a file would pass the
    // staleness check above, because there would be nothing to compare.
    expect(generateAll().map((f) => f.relPath).sort()).toEqual([
      'docs/booking/BOOKING_ACTOR_PERMISSION_MATRIX.md',
      'docs/booking/BOOKING_STATE_MACHINE.md',
      'docs/booking/BOOKING_STATUS_MIGRATION_MATRIX.md',
    ]);
  });

  it('every document carries the do-not-edit header', () => {
    for (const f of generateAll()) {
      expect(f.content).toContain('GENERATED FILE - do not edit by hand');
      expect(f.content).toContain('npm run booking:docs');
    }
  });
});

describe('the state machine document publishes the whole machine', () => {
  const doc = read('docs/booking/BOOKING_STATE_MACHINE.md');

  it('lists every canonical state', () => {
    for (const state of BOOKING_STATES) {
      expect(doc).toContain(`| \`${state}\` |`);
    }
  });

  it('lists every whitelisted transition', () => {
    for (const t of TRANSITIONS) {
      expect(doc).toContain(`| \`${t.from}\` | \`${t.to}\` | \`${t.action}\` |`);
    }
  });

  it('lists every action', () => {
    for (const action of Object.keys(BOOKING_ACTIONS)) {
      expect(doc).toContain(`\`${action}\``);
    }
  });

  it('states the counts, so a shrunken machine is visible in the prose', () => {
    expect(doc).toContain(`${BOOKING_STATES.length} states`);
    expect(doc).toContain(`${TRANSITIONS.length} whitelisted transitions`);
    expect(doc).toContain(`${Object.keys(BOOKING_ACTIONS).length} actions`);
  });

  it('records the executor ordering that the transaction depends on', () => {
    // The properties most easily lost in a later refactor.
    expect(doc).toContain('FOR UPDATE');
    expect(doc).toContain('advisory lock');
    expect(doc).toContain('AFTER the booking row');
    expect(doc).toContain('§45');
  });
});

describe('the permission matrix publishes every actor', () => {
  const doc = read('docs/booking/BOOKING_ACTOR_PERMISSION_MATRIX.md');

  it('covers each action with exactly one owning actor', () => {
    for (const [name, spec] of Object.entries(BOOKING_ACTIONS)) {
      const row = doc.split('\n').find((l) => l.startsWith(`| \`${name}\` |`));
      expect(row).toBeDefined();
      // Exactly one tick per action row: an action with two actors would be an
      // authorization hole, and the matrix would be hiding it.
      expect((row!.match(/✅/g) ?? []).length).toBe(1);
      expect(spec.actor).toBeTruthy();
    }
  });

  it('keeps the two authorization failures distinct', () => {
    expect(doc).toContain('NOT_AUTHORIZED');
    expect(doc).toContain('INVALID_TRANSITION');
  });
});

describe('the migration matrix is derived, not described', () => {
  const doc = read('docs/booking/BOOKING_STATUS_MIGRATION_MATRIX.md');

  it('publishes the ended-assignment rule that caused a real defect', () => {
    // A declined provider read as ASSIGNED and could accept the job again.
    expect(doc).toContain('DECLINED');
    expect(doc).toContain('REASSIGNED');
    expect(doc).toContain('AWAITING_ASSIGNMENT');
  });

  it('publishes the null / undefined worker_uid distinction', () => {
    expect(doc).toContain('`worker_uid` `null`');
    expect(doc).toContain('`worker_uid` `undefined`');
  });

  it('publishes the escalation override and the PAID/CONFIRMED collapse', () => {
    expect(doc).toContain('Escalation outranks everything');
    expect(doc).toContain('promotion trigger');
    expect(doc).toContain('TAB04_OPEN_GAPS.md');
  });

  it('shows an unrecognised status falling back to intake', () => {
    // The fallback is a design decision — surface it to an admin rather than
    // hide it — and an undocumented decision is free to change unnoticed.
    const row = doc.split('\n').find((l) => l.includes('SOME_UNRECOGNISED_STATUS'));
    expect(row).toBeDefined();
    expect(row).toContain('AWAITING_ASSIGNMENT');
  });
});
