"""Render the Command 3 §1 audit inventory to Markdown."""
import io, json, os, re, collections

HERE = os.path.dirname(__file__)
rows = json.load(io.open(os.path.join(HERE, "inventory.json"), encoding="utf-8"))
OUT = r"C:\Users\paulg\OneDrive\Desktop\servana_api-main\docs\SERVANA_PROVIDER_ENDPOINT_INVENTORY.md"

CANON_PREFIX = ("/api/worker/", "/api/provider/", "/api/providers/")
LEGACY_FILE = "routes/technician.routes.ts"


def fam(r):
    if r["file"] == LEGACY_FILE:
        return "legacy"
    if any(r["path"].startswith(p) for p in CANON_PREFIX):
        return "canonical"
    if "/admin/" in r["path"]:
        return "admin"
    return "shared"


for r in rows:
    r["family"] = fam(r)


def ident(r):
    if r.get("token"):
        return "token"
    if r.get("body_uid"):
        return "**body.uid**"
    if r.get("claimed"):
        return "path:" + ",".join(r["claimed"][:2])
    return "—"


def risk(r):
    auth = "verifyAuth" in r["mw"]
    if not auth and r["family"] == "legacy":
        return "P0"
    if not auth and "webhook" not in r["path"]:
        return "P1"
    if auth and not r.get("token") and r.get("claimed") and r["family"] != "admin":
        return "P2"
    return "—"


for r in rows:
    r["risk"] = risk(r)

L = []
w = L.append

w("# Servana provider API — endpoint audit inventory")
w("")
w("**Command 3 §1 deliverable. Audit only — this document changes no behaviour.**")
w("")
w("Generated by extraction from source, not by hand or from documentation, so it")
w("describes what the code does rather than what anything claims it does.")
w("")
w("## Scope and provenance")
w("")
w("| | |")
w("| --- | --- |")
w("| Backend | `PaulEspinas2020/servana_api` @ `6442b6e` (local == origin/main) |")
w("| Provider portal | `Upupapp/servana_service-provider` @ `42fbec9` |")
w("| Worker app | `Heatclift/ServanaWorker` @ `b94f7a1` |")
w("| Customer app | `Heatclift/ServanaClient` @ `0c8af75` |")
w("| Admin portal | `Upupapp/servana_adminportal` @ `f9ea07a` |")
w(f"| Provider-facing routes inventoried | **{len(rows)}** |")
w("| Backend routes in total | 392 across 27 routers |")
w("")
w("Everything mounts flat at `/api` (`app.ts:97-193`) — there is no per-router")
w("prefix, so each route file declares its own full sub-path. Route precedence is")
w("therefore file *mount order*, which matters for the wildcards noted below.")
w("")

# ---------------------------------------------------------------- summary
auth = sum(1 for r in rows if "verifyAuth" in r["mw"])
tok = sum(1 for r in rows if r.get("token"))
w("## Summary")
w("")
w("| Property | Count |")
w("| --- | ---: |")
w(f"| Requires authentication | {auth} |")
w(f"| **No authentication** | **{len(rows)-auth}** |")
w(f"| Identity derived from the token | {tok} |")
w(f"| Identity taken from the request | {len(rows)-tok} |")
w("")
byfam = collections.Counter(r["family"] for r in rows)
w("| Family | Count | Meaning |")
w("| --- | ---: | --- |")
w(f"| `canonical` | {byfam['canonical']} | `/api/worker/*`, `/api/provider/*` — auth-scoped, subject from token |")
legacy_noauth = sum(1 for r in rows if r["family"] == "legacy" and "verifyAuth" not in r["mw"])
w(f"| `legacy` | {byfam['legacy']} | `/api/workers/*` — subject from URL/query; **{legacy_noauth} of these have no auth at all**, the rest do |")
w(f"| `shared` | {byfam['shared']} | booking / payment / chat / catalog, used by several clients |")
w(f"| `admin` | {byfam['admin']} | role- and permission-gated |")
w("")

# ---------------------------------------------------------------- risk
w("## Risk register")
w("")
w("| Grade | Meaning | Count |")
w("| --- | --- | ---: |")
byrisk = collections.Counter(r["risk"] for r in rows)
w(f"| **P0** | No authentication, subject named by the caller | {byrisk['P0']} |")
w(f"| P1 | No authentication, not a webhook | {byrisk['P1']} |")
w(f"| P2 | Authenticated, but identity still taken from the request (BOLA surface) | {byrisk['P2']} |")
w(f"| — | No finding | {byrisk['—']} |")
w("")
w("### P0 — the legacy family")
w("")
w("All 30 sit in `technician.routes.ts`. They are already documented in")
w("`WORKER_ROUTE_MIGRATION.md`, have authenticated successors, and carry traffic")
w("telemetry (`legacyRouteTelemetry`). **Both client apps have now been migrated")
w("off them** (ServanaWorker `b94f7a1`, ServanaClient `0c8af75`), which was the")
w("blocker on deleting the block. They stay reachable until those builds are in")
w("the field and observed traffic reaches zero.")
w("")
w("Until then the exposure is live: anyone can read a provider's job cards —")
w("which carry the customer's name, phone number and home address — follow a")
w("provider's live position, or accept and complete bookings on their behalf.")
w("")

# ---------------------------------------------------------------- pagination
w("## Cross-cutting inconsistencies (Command 3 §16, §17)")
w("")
pag = [r for r in rows if r.get("paginated")]
qs = collections.Counter()
for r in rows:
    for q in r.get("query", []):
        qs[q] += 1
w(f"`limit`/`offset`/`page`/`cursor` appear in {len(pag)} handlers. The query")
w("parameters actually read across the provider surface:")
w("")
w("| Query parameter | Handlers reading it |")
w("| --- | ---: |")
for k, n in qs.most_common(22):
    w(f"| `{k}` | {n} |")
w("")
w("There is **no single pagination contract**. Standardising it is §16 work and")
w("belongs to the next phase, not this document.")
w("")

# ---------------------------------------------------------------- full table
w("## Full inventory")
w("")
w("`ident` is the audit's central column: where the handler gets the subject it")
w("acts on. `token` means the server decided; anything else means the caller did.")
w("")
for family in ("canonical", "legacy", "shared", "admin"):
    sub = [r for r in rows if r["family"] == family]
    if not sub:
        continue
    w(f"### `{family}` — {len(sub)} routes")
    w("")
    w("| Method | Path | Auth | ident | Controller | Query | Clients | Risk |")
    w("| --- | --- | --- | --- | --- | --- | --- | --- |")
    for r in sorted(sub, key=lambda r: (r["file"], r["line"])):
        a = "yes" if "verifyAuth" in r["mw"] else "**NO**"
        if "verifyRoles" in r["mw"]:
            a += " +role"
        if "requirePermission" in r["mw"]:
            a += " +perm"
        q = ",".join(f"`{x}`" for x in (r.get("query") or [])[:4]) or "—"
        cl = ",".join(r.get("clients") or []) or "—"
        ctl = r.get("controller") or "?"
        w(f"| {r['method']} | `{r['path']}` | {a} | {ident(r)} | `{ctl}` | {q} | {cl} | {r['risk']} |")
    w("")

# ---------------------------------------------------------------- limits
w("## What this audit could NOT determine")
w("")
w("Stated explicitly so nothing here is mistaken for more than it is.")
w("")
w("- **Response schemas are not fully typed.** The backend uses raw `pg` with no")
w("  ORM or serializer layer, so response shape is whatever each handler")
w("  assembles inline. Shapes were compared by reading handlers pairwise, not")
w("  derived from a schema. There is no generated contract to diff against — that")
w("  is what §3 (OpenAPI) would create.")
w("- **`clients` is textual.** A path appearing in a repository is not proof a")
w("  screen reaches it. The provider portal, for instance, lists the whole legacy")
w("  family in `servana-backend-capabilities.config.ts`, which is a catalogue and")
w("  not a call site. Live callers were confirmed by hand only where a finding")
w("  depended on it.")
w("- **Ownership enforcement inside services was not traced end to end.** Several")
w("  handlers take a path id under `verifyAuth` and enforce ownership in SQL")
w("  (`WHERE worker_uid = $1`). That is correct but invisible at this level, so a")
w("  P2 grade means *worth tracing*, not *proven vulnerable*.")
w("- **Status vocabularies were not reconciled.** That is §6 and needs the")
w("  database's own constraints, not route source.")
w("")
w("## Corrections this audit makes to earlier records")
w("")
w("- **Command 2 recorded that job actions send `?workerUid=` and marked it")
w("  UNVERIFIED whether the backend trusts it.** It does not:")
w("  `actingWorkerUid` (`technicianController.ts:510`) returns `fromToken ?? null`")
w("  and logs a mismatch. The parameter was decorative. Now removed client-side.")
w("- **An earlier pass of this audit reported all 10 chat routes as")
w("  unauthenticated.** That was wrong. `chat.routes.ts:8` applies")
w("  `router.use(verifyAuth)` at the router level; the extractor only inspected")
w("  per-route middleware. Corrected, and the extractor now counts router-level")
w("  middleware. No chat vulnerability exists.")
w("- **`GET /api/:id` (`booking.routes.ts:44`) is a bare single-segment wildcard**")
w("  registered before 15 other routers. It shadows nothing *today* — no later")
w("  router declares a competing single-segment GET — but any future one would be")
w("  silently swallowed. Latent, not live.")
w("")

io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(L) + "\n")
print("wrote", OUT)
print("lines:", len(L))
