/**
 * Execute migrations 041 and 042 on a real PostgreSQL. Nothing else does.
 *
 * Same reason as 039 and 040: `db:verify:embedded` seeds DML-only migrations
 * into its ledger as already applied, so a data migration would otherwise
 * reach production having never run anywhere.
 *
 * They are rehearsed TOGETHER because they are one decision — 041 brings
 * Plumbing and Carpentry live, 042 retires the four duplicates — and because
 * 042's guards read state 041 creates: retiring a family that has just been
 * given an offering mapping must fail, and only running both proves it does.
 *
 * Run: npm run migration:041-042:rehearse
 */

import fs from 'fs';
import path from 'path';

import { createEngine, RUNTIME_ROLE, TARGET_SCHEMA } from './lib/embeddedEngine';

const read = (file: string) =>
  fs.readFileSync(path.resolve(__dirname, 'migrations', file), 'utf8');

const M041 = read('041-home-maintenance-plumbing-carpentry.sql');
const M042 = read('042-retire-duplicate-service-families.sql');

/**
 * The five tables these migrations touch, from `scripts/baseline/000-baseline.sql`.
 *
 * The UNIQUE on `(offering_id, service_id, level_2)` is copied verbatim — it is
 * what makes 041's `ON CONFLICT DO NOTHING` idempotent rather than duplicating,
 * and a simplified table would let the rehearsal pass and production diverge.
 */
const SCHEMA_SQL = `
CREATE TABLE ${TARGET_SCHEMA}.service_families (
  id integer NOT NULL PRIMARY KEY,
  name character varying NOT NULL,
  category character varying,
  created_at timestamptz DEFAULT NOW(),
  deleted_at timestamptz
);

CREATE TABLE ${TARGET_SCHEMA}.service_options (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id integer NOT NULL,
  option_type character varying NOT NULL,
  level_3 character varying,
  is_active boolean DEFAULT true
);

CREATE TABLE ${TARGET_SCHEMA}.catalog_categories (
  id integer NOT NULL PRIMARY KEY,
  name character varying NOT NULL,
  status character varying NOT NULL
    CHECK (status IN ('draft','active','inactive','archived'))
);

CREATE TABLE ${TARGET_SCHEMA}.catalog_subcategories (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id integer NOT NULL,
  name character varying NOT NULL,
  slug character varying,
  display_order integer DEFAULT 0,
  status character varying NOT NULL
    CHECK (status IN ('draft','active','inactive','archived')),
  legacy_service_family_id integer,
  created_at timestamptz DEFAULT NOW(),
  updated_at timestamptz DEFAULT NOW(),
  archived_at timestamptz
);

CREATE TABLE ${TARGET_SCHEMA}.service_coverage_geo (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id integer NOT NULL,
  center_lat numeric NOT NULL,
  center_lon numeric NOT NULL,
  radius_km numeric NOT NULL,
  is_active boolean DEFAULT true
);

CREATE TABLE ${TARGET_SCHEMA}.provider_catalog_offerings (
  id integer NOT NULL PRIMARY KEY,
  name character varying NOT NULL,
  status character varying NOT NULL,
  provider_web_visible boolean NOT NULL DEFAULT true
);

CREATE TABLE ${TARGET_SCHEMA}.provider_catalog_offering_mappings (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  offering_id integer NOT NULL REFERENCES ${TARGET_SCHEMA}.provider_catalog_offerings(id),
  service_id integer NOT NULL,
  level_2 character varying NOT NULL,
  display_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  UNIQUE (offering_id, service_id, level_2)
);

CREATE TABLE ${TARGET_SCHEMA}.employee_services (
  employee_uid text NOT NULL,
  service_id integer NOT NULL
);
`;

/** Production on 2026-08-20, trimmed to what these two migrations read. */
const SEED = `
INSERT INTO ${TARGET_SCHEMA}.service_families (id, name, category) VALUES
  ( 1, 'Aircon 2',            'Home Services'),
  ( 2, 'Beauty & Wellness',   'Personal Care'),
  (53, 'Hair',                'Personal Care'),
  (54, 'Nails',               'Personal Care'),
  (66, 'Aesthetics & Beauty', 'Beauty & Wellness'),
  (67, 'Electrical Services', 'Home Maintenance'),
  (68, 'Barbering',           'Beauty & Wellness'),
  (69, 'Plumbing',            'Home Maintenance'),
  (70, 'Carpentry',           'Home Maintenance');

-- Only 1, 2 and 67 carry services.
INSERT INTO ${TARGET_SCHEMA}.service_options (service_id, option_type, level_3) VALUES
  ( 1, 'MAIN', 'Aircon Cleaning'),
  ( 2, 'MAIN', 'Body Massage'),
  (67, 'MAIN', 'Wiring fuitures');

INSERT INTO ${TARGET_SCHEMA}.catalog_categories (id, name, status) VALUES
  (1, 'Home Maintenance', 'active'),
  (3, 'Personal Care',    'active');

INSERT INTO ${TARGET_SCHEMA}.catalog_subcategories
  (id, category_id, name, slug, status, legacy_service_family_id) VALUES
  (1, 1, 'Electrical', 'electrical', 'active', 67),
  (9, 3, 'Hair',       'hair',       'active',  2);

INSERT INTO ${TARGET_SCHEMA}.provider_catalog_offerings (id, name, status, provider_web_visible) VALUES
  (2, 'Plumbing',            'active', true),
  (3, 'Electrical Services', 'active', true),
  (6, 'Hair Services',       'active', true),
  (8, 'Carpentry & Fixer',   'active', true);

-- The mappings that DID resolve. 2 and 8 are the ones the seed skipped.
INSERT INTO ${TARGET_SCHEMA}.provider_catalog_offering_mappings (offering_id, service_id, level_2) VALUES
  (3, 67, 'Electrical'),
  (6,  2, 'Hair');

-- Every provider on a to-be-retired family also holds family 2, as measured.
INSERT INTO ${TARGET_SCHEMA}.employee_services (employee_uid, service_id) VALUES
  ('hair-1', 53), ('hair-1', 2),
  ('nail-1', 54), ('nail-1', 2),
  ('aes-1',  66), ('aes-1',  2),
  ('barb-1', 68), ('barb-1', 2);

-- Advance the identity sequences past the ids seeded explicitly above.
--
-- Not cosmetic. Without it the first INSERT that lets the sequence choose an id
-- collides with a seeded row, and 041 fails on the catalog_subcategories
-- primary key — which is what happened on the first run of this rehearsal.
-- (No backticks in this comment: it lives inside a JS template literal, and a
-- backtick would end the string.)
-- Production is safe (measured: max id 12, sequence at 24), and
-- modelling that is the point: a rehearsal whose sequences are BEHIND
-- production's tests a failure production cannot have, and one whose sequences
-- are ahead would hide a failure it can.
SELECT setval(pg_get_serial_sequence('${TARGET_SCHEMA}.catalog_subcategories', 'id'),
              (SELECT MAX(id) FROM ${TARGET_SCHEMA}.catalog_subcategories));
SELECT setval(pg_get_serial_sequence('${TARGET_SCHEMA}.provider_catalog_offering_mappings', 'id'),
              (SELECT COALESCE(MAX(id), 1) FROM ${TARGET_SCHEMA}.provider_catalog_offering_mappings));
SELECT setval(pg_get_serial_sequence('${TARGET_SCHEMA}.service_coverage_geo', 'id'),
              (SELECT COALESCE(MAX(id), 1) FROM ${TARGET_SCHEMA}.service_coverage_geo));
`;

type Engine = Awaited<ReturnType<typeof createEngine>>;

const freshDatabase = async (extra = ''): Promise<Engine> => {
  const db = await createEngine();
  await db.exec(
    `CREATE ROLE ${RUNTIME_ROLE};
     CREATE SCHEMA IF NOT EXISTS ${TARGET_SCHEMA} AUTHORIZATION ${RUNTIME_ROLE};`,
  );
  await db.exec(SCHEMA_SQL);
  await db.exec(SEED);
  if (extra) await db.exec(extra);
  return db;
};

const scalar = async (db: Engine, sql: string): Promise<string> => {
  const result: any = await db.query(sql);
  return String(Object.values(result.rows[0] ?? {})[0] ?? '');
};

const failures: string[] = [];

const check = (name: string, condition: boolean, detail = ''): void => {
  if (condition) {
    console.log(`    pass  ${name}`);
  } else {
    console.log(`    FAIL  ${name}${detail ? ` — ${detail}` : ''}`);
    failures.push(name);
  }
};

/** Applies SQL, reporting a throw as a named failure rather than a raw dump. */
const apply = async (db: Engine, sql: string, what: string): Promise<boolean> => {
  try {
    await db.exec(sql);
    return true;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    check(what, false, message.split('\n')[0]);
    return false;
  }
};

async function main(): Promise<void> {
  console.log('\nServana — executed rehearsal of 041 + 042');
  console.log('  EMBEDDED PostgreSQL (PGlite, in-process)\n');

  // ── 041 ────────────────────────────────────────────────────────────────────
  console.log('  041 · Plumbing and Carpentry into Home Maintenance');
  {
    const db = await freshDatabase();
    try {
      check('starts with offerings 2 and 8 mapped to nothing',
        (await scalar(db, `SELECT COUNT(*) FROM ${TARGET_SCHEMA}.provider_catalog_offering_mappings
                            WHERE offering_id IN (2, 8)`)) === '0');

      if (!(await apply(db, M041, '041 runs'))) return;

      check('offering 2 now maps to family 69',
        (await scalar(db, `SELECT service_id FROM ${TARGET_SCHEMA}.provider_catalog_offering_mappings
                            WHERE offering_id = 2`)) === '69');
      check('offering 8 now maps to family 70',
        (await scalar(db, `SELECT service_id FROM ${TARGET_SCHEMA}.provider_catalog_offering_mappings
                            WHERE offering_id = 8`)) === '70');

      check('both subcategories are under Home Maintenance',
        (await scalar(db, `SELECT COUNT(*) FROM ${TARGET_SCHEMA}.catalog_subcategories
                            WHERE legacy_service_family_id IN (69,70) AND category_id = 1`)) === '2');

      // The customer-facing promise. An ACTIVE empty section would put
      // "Plumbing (0)" in front of every customer browsing Home Maintenance.
      check('neither is visible to customers yet (draft)',
        (await scalar(db, `SELECT COUNT(*) FROM ${TARGET_SCHEMA}.catalog_subcategories
                            WHERE legacy_service_family_id IN (69,70) AND status = 'active'`)) === '0');

      check('both families have Metro Manila coverage',
        (await scalar(db, `SELECT COUNT(*) FROM ${TARGET_SCHEMA}.service_coverage_geo
                            WHERE service_id IN (69,70) AND radius_km = 50 AND is_active`)) === '2');

      check('nothing new is on sale — no services were invented',
        (await scalar(db, `SELECT COUNT(*) FROM ${TARGET_SCHEMA}.service_options
                            WHERE service_id IN (69,70)`)) === '0');
    } finally {
      await db.close();
    }
  }

  {
    const db = await freshDatabase();
    try {
      await db.exec(M041);
      const before = await scalar(db,
        `SELECT COUNT(*) FROM ${TARGET_SCHEMA}.provider_catalog_offering_mappings`);
      await db.exec(M041);
      await db.exec(M041);
      const after = await scalar(db,
        `SELECT COUNT(*) FROM ${TARGET_SCHEMA}.provider_catalog_offering_mappings`);
      check('041 is idempotent over three runs', before === after, `${before} then ${after}`);
    } finally {
      await db.close();
    }
  }

  // ── 042 ────────────────────────────────────────────────────────────────────
  console.log('\n  042 · retire the four duplicates');
  {
    const db = await freshDatabase();
    try {
      if (!(await apply(db, M042, '042 runs'))) return;

      check('all four are retired',
        (await scalar(db, `SELECT COUNT(*) FROM ${TARGET_SCHEMA}.service_families
                            WHERE id IN (53,54,66,68) AND deleted_at IS NOT NULL`)) === '4');

      check('the families that sell things are untouched',
        (await scalar(db, `SELECT COUNT(*) FROM ${TARGET_SCHEMA}.service_families
                            WHERE id IN (1,2,67) AND deleted_at IS NULL`)) === '3');

      check('69 and 70 are NOT retired — they are being brought live',
        (await scalar(db, `SELECT COUNT(*) FROM ${TARGET_SCHEMA}.service_families
                            WHERE id IN (69,70) AND deleted_at IS NULL`)) === '2');

      check('every provider keeps a live family to work through',
        (await scalar(db, `SELECT COUNT(DISTINCT e.employee_uid)
                             FROM ${TARGET_SCHEMA}.employee_services e
                            WHERE e.service_id IN (53,54,66,68)
                              AND NOT EXISTS (SELECT 1 FROM ${TARGET_SCHEMA}.employee_services l
                                              JOIN ${TARGET_SCHEMA}.service_families f ON f.id = l.service_id
                                             WHERE l.employee_uid = e.employee_uid AND f.deleted_at IS NULL)`)) === '0');

      check('nothing is deleted — the rows survive',
        (await scalar(db, `SELECT COUNT(*) FROM ${TARGET_SCHEMA}.service_families`)) === '9');
    } finally {
      await db.close();
    }
  }

  {
    const db = await freshDatabase();
    try {
      await db.exec(M042);
      const first = await scalar(db,
        `SELECT MAX(deleted_at)::text FROM ${TARGET_SCHEMA}.service_families WHERE id = 53`);
      await db.exec(M042);
      const second = await scalar(db,
        `SELECT MAX(deleted_at)::text FROM ${TARGET_SCHEMA}.service_families WHERE id = 53`);
      check('042 is idempotent', first === second, `${first} then ${second}`);
    } finally {
      await db.close();
    }
  }

  // ── The guard that matters most ────────────────────────────────────────────
  console.log('\n  042 · refuses to retire a family that is no longer empty');
  {
    // A family that has acquired a service since this was written is not a
    // duplicate of anything, and must not be retired by an id that was true
    // last week.
    const db = await freshDatabase(
      `INSERT INTO ${TARGET_SCHEMA}.service_options (service_id, option_type, level_3)
       VALUES (54, 'MAIN', 'Gel Extensions');`,
    );
    try {
      let threw = '';
      try {
        await db.exec(M042);
      } catch (error) {
        threw = error instanceof Error ? error.message : String(error);
      }
      check('a family that gained a service is refused',
        /expected 4/i.test(threw), threw.split('\n')[0] || 'it did not throw');
      check('and nothing was retired',
        (await scalar(db, `SELECT COUNT(*) FROM ${TARGET_SCHEMA}.service_families
                            WHERE deleted_at IS NOT NULL`)) === '0');
    } finally {
      await db.close();
    }
  }

  {
    // A provider with no live family must block the retirement rather than
    // lose every job they can do.
    const db = await freshDatabase(
      `INSERT INTO ${TARGET_SCHEMA}.employee_services (employee_uid, service_id)
       VALUES ('only-hair', 53);`,
    );
    try {
      let threw = '';
      try {
        await db.exec(M042);
      } catch (error) {
        threw = error instanceof Error ? error.message : String(error);
      }
      check('a provider who would be stranded blocks it',
        /would lose all assignable work/i.test(threw),
        threw.split('\n')[0] || 'it did not throw');
    } finally {
      await db.close();
    }
  }

  // ── Both, in order ─────────────────────────────────────────────────────────
  console.log('\n  041 then 042, as they will be applied');
  {
    const db = await freshDatabase();
    try {
      if (!(await apply(db, M041, '041 runs first'))) return;
      if (!(await apply(db, M042, '042 runs after it'))) return;

      check('four retired, and Plumbing and Carpentry live',
        (await scalar(db, `SELECT COUNT(*) FROM ${TARGET_SCHEMA}.service_families
                            WHERE deleted_at IS NULL`)) === '5');
      check('the survivors are 1, 2, 67, 69, 70',
        (await scalar(db, `SELECT string_agg(id::text, ',' ORDER BY id)
                             FROM ${TARGET_SCHEMA}.service_families WHERE deleted_at IS NULL`))
          === '1,2,67,69,70');
    } finally {
      await db.close();
    }
  }

  console.log(
    `\n  RESULT: ${failures.length === 0 ? 'PASS' : `FAIL — ${failures.join(', ')}`}\n`,
  );
  if (failures.length) process.exitCode = 1;
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
