/**
 * Execute migration 039 on a real PostgreSQL. Nothing else does.
 *
 * Run: npm run migration:039:rehearse
 *
 * ## Why this exists
 *
 * `npm run db:verify:embedded` does NOT run this migration, and reported PASS
 * on a run in which its SQL never executed.
 *
 * The fresh-database rehearsal seeds its ledger from `verify-baseline-ledger`,
 * which classifies each migration by the schema objects it declares. 039
 * declares none, so it lands in the "no schema effect" bucket with fourteen
 * other data migrations and is marked applied before the chain runs. The
 * checker is explicit about the limit of its own verdict:
 *
 *   "These change data rather than schema, so the baseline cannot confirm
 *    them. They need a human judgement, not a green tick."
 *
 * Right classification, wrong amount of coverage. A data migration that is
 * never executed anywhere is a data migration whose first run is production.
 *
 * ## Why a script and not a Jest test
 *
 * PGlite loads its WASM through a dynamic `import()`, which Jest's VM refuses
 * without `--experimental-vm-modules`. `tests/schema-baseline-engine.test.ts`
 * already records the decision not to turn that on for a 250-suite run to
 * accommodate one file, and puts the executed replay in a ts-node script
 * instead. This follows that.
 *
 * PGlite is PostgreSQL 18 compiled to WebAssembly, so the SQL below is parsed,
 * planned and executed by the real engine — numeric comparison included, which
 * is the part that decides whether the idempotency guard actually holds.
 *
 * ## Exit codes
 *
 *   0 — every assertion held.
 *   1 — one did not. The output names which.
 */

import fs from 'fs';
import path from 'path';

import { createEngine, RUNTIME_ROLE, TARGET_SCHEMA } from './lib/embeddedEngine';

const MIGRATION_FILE = '039-electrical-service-coverage.sql';

const MIGRATION = fs.readFileSync(
  path.resolve(__dirname, 'migrations', MIGRATION_FILE),
  'utf8',
);

/**
 * The two tables 039 touches, copied from `scripts/baseline/000-baseline.sql`.
 *
 * Not a hand-simplified shape: `center_lat`, `center_lon` and `radius_km` are
 * `numeric NOT NULL` there, and numeric is precisely what makes the equality in
 * the migration's `WHERE NOT EXISTS` worth executing — comparing 14.5547 as
 * numeric is not the same question as comparing it as a float.
 */
const SCHEMA_SQL = `
CREATE TABLE ${TARGET_SCHEMA}.service_families (
  id integer NOT NULL PRIMARY KEY,
  name character varying,
  category character varying
);

CREATE TABLE ${TARGET_SCHEMA}.service_coverage_geo (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id integer NOT NULL,
  center_lat numeric NOT NULL,
  center_lon numeric NOT NULL,
  radius_km numeric NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now()
);
`;

/** Production's rows for family 1 on 2026-08-20, which 039 mirrors onto 67. */
const FAMILY_1_COVERAGE = `
INSERT INTO ${TARGET_SCHEMA}.service_coverage_geo
  (service_id, center_lat, center_lon, radius_km, is_active)
VALUES
  (1, 14.5547, 121.0244,  25, TRUE),
  (1, 16.5,    121.5,    600, TRUE),
  (1, 11.0,    123.5,    400, TRUE),
  (1,  7.0,    123.5,    600, TRUE),
  (1, 10.0,    118.5,    350, TRUE);
`;

type Engine = Awaited<ReturnType<typeof createEngine>>;
type Row = { lat: string; lon: string; radius: string; is_active: boolean };

const freshDatabase = async (withFamily67: boolean): Promise<Engine> => {
  const db = await createEngine();
  await db.exec(
    `CREATE ROLE ${RUNTIME_ROLE};
     CREATE SCHEMA IF NOT EXISTS ${TARGET_SCHEMA} AUTHORIZATION ${RUNTIME_ROLE};`,
  );
  await db.exec(SCHEMA_SQL);
  await db.exec(
    `INSERT INTO ${TARGET_SCHEMA}.service_families (id, name, category) VALUES
       (1, 'Aircon 2', 'Home Services'),
       (2, 'Beauty & Wellness', 'Personal Care')${
         withFamily67 ? `, (67, 'Electrical Services', 'Home Maintenance')` : ''
       };`,
  );
  await db.exec(FAMILY_1_COVERAGE);
  return db;
};

const coverageFor = async (db: Engine, serviceId: number): Promise<Row[]> => {
  const result: any = await db.query(
    `SELECT center_lat::text AS lat, center_lon::text AS lon,
            radius_km::text AS radius, is_active
       FROM ${TARGET_SCHEMA}.service_coverage_geo
      WHERE service_id = $1
      ORDER BY radius_km, center_lat`,
    [serviceId],
  );
  return result.rows as Row[];
};

/**
 * The distance test `serviceService.checkCoverageGeo` performs, in the same
 * spherical form — so "is Manila covered" is answered by the geometry rather
 * than by counting rows.
 */
const covers = (rows: Row[], lat: number, lon: number): boolean =>
  rows.some((row) => {
    const rad = (d: number) => (d * Math.PI) / 180;
    const distance =
      6371 *
      Math.acos(
        Math.min(
          1,
          Math.max(
            -1,
            Math.cos(rad(lat)) *
              Math.cos(rad(Number(row.lat))) *
              Math.cos(rad(Number(row.lon)) - rad(lon)) +
              Math.sin(rad(lat)) * Math.sin(rad(Number(row.lat))),
          ),
        ),
      );
    return distance <= Number(row.radius);
  });

const MANILA: [number, number] = [14.5547, 121.0244];
const CEBU: [number, number] = [10.3157, 123.8854];
const DAVAO: [number, number] = [7.1907, 125.4553];

const failures: string[] = [];

const check = (name: string, condition: boolean, detail = ''): void => {
  if (condition) {
    console.log(`    pass  ${name}`);
  } else {
    console.log(`    FAIL  ${name}${detail ? ` — ${detail}` : ''}`);
    failures.push(name);
  }
};

async function main(): Promise<void> {
  console.log(`\nServana — executed rehearsal of ${MIGRATION_FILE}`);
  console.log('  EMBEDDED PostgreSQL (PGlite, in-process)\n');

  // ── The defect it starts from ──────────────────────────────────────────────
  //
  // Without this, everything below could pass against a database that never
  // had the problem.
  {
    const db = await freshDatabase(true);
    try {
      const before = await coverageFor(db, 67);
      check('starts uncovered', before.length === 0, `${before.length} rows`);
      check('Manila not covered before', !covers(before, ...MANILA));
    } finally {
      await db.close();
    }
  }

  // ── What it does ───────────────────────────────────────────────────────────
  {
    const db = await freshDatabase(true);
    try {
      await db.exec(MIGRATION);
      const after = await coverageFor(db, 67);

      check('inserts five discs', after.length === 5, `${after.length} rows`);
      check('all active', after.every((r) => r.is_active));
      check('Manila covered', covers(after, ...MANILA));
      check('Cebu covered', covers(after, ...CEBU));
      check('Davao covered', covers(after, ...DAVAO));

      // Its whole claim is that it completes an expansion pass which missed
      // this family — not that it invents a service area. Compared as text so
      // a numeric scale difference cannot hide a mismatch.
      const family1 = await coverageFor(db, 1);
      check(
        'geometry identical to family 1',
        JSON.stringify(after.map((r) => [r.lat, r.lon, r.radius])) ===
          JSON.stringify(family1.map((r) => [r.lat, r.lon, r.radius])),
        JSON.stringify(after.map((r) => [r.lat, r.lon, r.radius])),
      );
    } finally {
      await db.close();
    }
  }

  // ── Idempotency ────────────────────────────────────────────────────────────
  //
  // `service_coverage_geo` carries NO unique constraint. Only the migration's
  // own `WHERE NOT EXISTS` prevents duplicates, and a duplicate would be
  // silent: coverage still evaluates the same and the rows simply accumulate.
  {
    const db = await freshDatabase(true);
    try {
      await db.exec(MIGRATION);
      await db.exec(MIGRATION);
      await db.exec(MIGRATION);
      const after = await coverageFor(db, 67);
      check('idempotent over three runs', after.length === 5, `${after.length} rows`);
    } finally {
      await db.close();
    }
  }

  // ── Blast radius ───────────────────────────────────────────────────────────
  {
    const db = await freshDatabase(true);
    try {
      const before = await coverageFor(db, 1);
      await db.exec(MIGRATION);
      check(
        'family 1 untouched',
        JSON.stringify(await coverageFor(db, 1)) === JSON.stringify(before),
      );
      check('family 2 untouched', (await coverageFor(db, 2)).length === 0);
    } finally {
      await db.close();
    }
  }

  // ── The postcondition ──────────────────────────────────────────────────────
  //
  // Every guard in the migration is a silent skip. Without the postcondition it
  // would insert nothing, exit 0, and be written into the ledger — and the
  // runner only applies what the ledger lacks, so it would never be retried. A
  // no-op recorded as applied is worse than a failure.
  {
    const db = await freshDatabase(false);
    try {
      let threw = '';
      try {
        await db.exec(MIGRATION);
      } catch (error) {
        threw = error instanceof Error ? error.message : String(error);
      }
      check(
        'refuses a silent no-op when family 67 is absent',
        /postcondition failed/i.test(threw),
        threw ? threw.split('\n')[0] : 'it did not throw',
      );
      check('and inserts nothing', (await coverageFor(db, 67)).length === 0);
    } finally {
      await db.close();
    }
  }

  console.log(
    `\n  RESULT: ${failures.length === 0 ? 'PASS' : `FAIL — ${failures.join(', ')}`}\n`,
  );
  if (failures.length) process.exitCode = 1;
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
